kkrn_objs+=obj/x86/entry.o obj/x86/mem.o obj/x86/cmem.o obj/x86/arch.o obj/x86/realprot.o obj/x86/intr_tab.o obj/x86/intr.o obj/x86/cintr.o obj/x86/port.o obj/x86/kern_vars.o obj/x86/x86minilib.o
ARCH_CFLAGS=-falign-jumps=1 -falign-loops=1 -falign-functions=1 -m32
ARCH_LDFLAGS=-Wl,-N -Wl,-Tos/src/x86/link.ld -m32

